require("user.options")
require("user.lazy")
require("user.keymaps")
require("user.highlight_yank")
require("user.resize_windows")
require("user.rotate_windows")
require("user.toggle_diagnostics")
require("user.autocmds")
